- components/header.js
- index.html
- product.html
** Added basic topbar and linked it to the html pages.
Review plz
> Ec 8 create header

- .gitignore
- components/header.js
**Added more styling to the topbar 
Review plz
> Ec 8 create header styling

- product.html
Added basic structure and content.
> Added structure

- components/footer.js
changed width to 100% instead of 100vw to fix overflow of footer and child elements
> changed to 100% in width instead of 100vw in css

- product.html
- styles/product.css
Added grid system with bootstrap, and some styling.
> Ec 10 styling product page

- components/footer.js
- index.html
- styles/global.css
changed colors to variables where applicable
> Add variables to css

- components/header.js
Used to css varibles declared in global.css instead of setting colors
> Converted colors to variables

- components/footer.js
changed position in footer.js from absolute to relative to fix footer covering content
> Changed footer position

- styles/product.css
Change viewheight on main content to fix footer position.
> Changed viewheight on main container

- styles/global.css
- styles/product.css
Added styling to main conatiner in global.css.
> Global styling

- components/header.js
> Added position sticky to topbar

- components/footer.js
added a class to links in list and gave that class css to change the color
> fixed color of product links 

- vite-app/src/App.jsx
- vite-app/src/components/header.jsx
- vite-app/src/styles/header.css
> Ec 25 migrate header

- vite-app/src/App.jsx
- vite-app/src/pages/product.jsx
> Migrating to react

- vite-app/src/pages/product.jsx
> Added style to "add to cart"-button

- vite-app/src/App.jsx
- vite-app/src/components/header.jsx
- vite-app/src/components/product.jsx
- vite-app/src/pages/category.jsx
- vite-app/src/styles/ProductComp.css
- vite-app/src/utils/functions.js
Created new component and category page layout and also started styling
> Ec 21 create category page

- vite-app/src/pages/product.jsx
- vite-app/src/styles/header.css
- vite-app/src/styles/product.css
Created API to get specific product to the product page. Added styling. Also added local staroage for adding products to the cart.
> Ec 17 use specific api in product page

- vite-app/package-lock.json
- vite-app/package.json
- vite-app/src/components/product.jsx
- vite-app/src/pages/home.jsx
- vite-app/src/styles/ProductComp.css
- vite-app/src/utils/functions.js
Also added some styling to product component.
> Added search results to home page

- package-lock.json
- vite-app/src/components/header.jsx
- vite-app/src/pages/home.jsx
- vite-app/src/styles/header.css
Added logo and cart icon to header
> Added logo and cart icon to header

- vite-app/src/components/header.jsx
> Hot fix for header cart crashing the site

- vite-app/src/App.jsx
- vite-app/src/components/header.jsx
- vite-app/src/main.jsx
- vite-app/src/providers/CartProvider.jsx
Created a global state provider for the cart, implement in product page with import {useCart} from "../providers/CartProvider.jsx" then const {cart} = useCart()
cart.addToCart(product)
> Created cartContext to save cart info

- vite-app/src/components/cartComp.jsx
- vite-app/src/components/header.jsx
- vite-app/src/pages/product.jsx
- vite-app/src/providers/CartProvider.jsx
Made a cart dropdown in the header to display cart and edit it
> Added cart dropdown in the header

- vite-app/src/custom.scss
- vite-app/src/pages/product.jsx
- vite-app/src/styles/product.css
Style finished. Added a breadcrumb and fixed some styles that disappeared in last merge.
> Ec 54 finish styling product page

- vite-app/src/components/footer.jsx
Added last styling to footer. Added logo and removed beige section of footer
> Finished footer 

- vite-app/src/App.jsx
- vite-app/src/pages/404.jsx
Added 404 page from bootstrap template
> Created 404 page

- vite-app/src/App.jsx
- vite-app/src/pages/product.jsx
- vite-app/src/pages/productError.jsx
- vite-app/src/pages/productNotFound.jsx
> Product not found
